### ISSUE TITLE
Memory leaking issue

### ISSUE THREAD

**Issue by BDMorrell** [izuzak/atom-pdf-view#101]
Ok, so I'm pretty new to gitHub, (this being my first public outreach) so this may not be well put. I'm pretty sure Issues is where you put bug reports.
In addition, I'm scared to open an issue directly to the atom repo before I rule this out.

*This error may actually be an atom or electron issue.*

Using [LaTeX](https://en.wikipedia.org/wiki/LaTeX), (a typesetting program) in atom (using the [latex](https://github.com/thomasjo/atom-latex) package), and viewing the result with this package, and refreshing every few minutes, my petty 2 GB of RAM started spilling into my swap; far too much memory needed for this package. The most memory usage was from atom's rendering ~~thread~~ process

I came here with the though that maybe you can shed some insight into what may be going on here. My thought is that JavaScript's garbage collection is unable to work properly.

I don't think the error is from PDF.js, as I can't find anything like this problem.
I identified the program as the atom rendering thread by it's initial arguments.
Note: I'm using atom version 1.2.0 with this package's version of 0.37.0 on Linux.

**Comment by izuzak** [comment]
Hi @BDMorrell :wave:. This sounds similar to another report: https://github.com/izuzak/atom-pdf-view/issues/72. Can you give that a read and add your comment there? I'd be happy to try and reproduce this again, but I'd need _exact_ and _detailed_ steps to reproduce and the exact documents you're reproducing this with, so that we could confirm if this is a problem with this package or not. Thanks!

**Comment by BDMorrell** [comment]
Sorry, I guess I need to learn how to use the search better. I'm pretty sure I tried searching for something like this before I posted it.
