### ISSUE TITLE
Confusion on how to implement synctex

### ISSUE THREAD

**Issue by HHHit** [izuzak/atom-pdf-view#151]
Hello，
 I am using Atom to compile Latex, however the synctex doesn't work. 
In the manual the author referred to some configuration on PATH. 
Could anybody make a more detailed explanation on it?

Thanks~!

**Comment by izuzak** [comment]
@HHHit Was the PDF you're looking at created with the `--synctex=1` option and do you have the `synctex` program on your machine? If so, then if you open the settings for this package in Atom, you can configure where the `synctex` program is located there (i.e. the path for the program). Have you tried doing that and it didn't work? If that's correctly configured, then try restarting Atom and see if it works. If it doesn't -- then I'm not sure what might be the problem. If you'd like, you could post the PDF and the source here so that someone else can try reproducing the issue.

Also, it would be helpful if you could post the version of Atom and this package you're using, and your OS+version.

**Comment by HHHit** [comment]
Thks a lot!
I have added a line at the top of source code: \synctex=1 and it still doesn't work. When I  click on the pdf, another blank page come out.
As to the **synctex** you referred to, is it the profile generated after compile or something else?

**Comment by izuzak** [comment]
> As to the synctex you referred to, is it the profile generated after compile or something else?

Which profile are you referring to and how is that relevant? In any case, I can't offer much advice about synctex. Synctex work fine for me, and you haven't provided any answers to the questions I asked in my previous message. If you can provide more information and clear reproduction steps -- I'd be happy to reopen this.

**Comment by hasantahir** [comment]
Hi,

I have run into the same issue where I think I don't know how to configure the path. My LaTeX setup is MikTeX 2.9.on windows 10 operating system with Atom version 1.12.6. Passing the parameter --synctex=1 during the compilation doesn't trigger anything from the generated pdf. I must mention that synctex runs fine with TeXworks.

Thank you.

**Comment by izuzak** [comment]
@hasantahir Sorry for not responding to your question sooner. I'm afraid I can't help you there -- I'm not familiar with *TeX setups and the synctex feature was added by a contributor to this package. If someone else watching this repository can help you debug -- that would be great. If you've already figured out things -- please post some notes for other folks who might run into the same problem. Thanks!

**Comment by ig0774** [comment]
The synctex feature, unfortunately, depends on the `synctex` binary provided by TeXLive, but not provided by MiKTeX. Synctex usually works with most synctex-aware PDF viewers because they tend to contain a linked version of the [synctex library](http://itexmac.sourceforge.net/SyncTeX.html). The only way I'm aware of to get things working on MiKTeX is to install TeXLive and copy the `synctex.exe` file somewhere then uninstall TeXLive (`synctex.exe` may have other dependencies; I can't check atm).

**Comment by mattkang** [comment]
@ig0774 I just wanted to confirm that this does indeed work. You need to copy two files to your MiKTeX path:
- synctex.exe
- kpathsea622.dll
