### ISSUE TITLE
Atom not freeing memory when closing the pdf tab

### ISSUE THREAD

**Issue by adimol** [izuzak/atom-pdf-view#186]
Generally, atom uses between 50-150 MB to open a pdf, as I can see in the system monitor tool (Linux). When the pdf tab is closed, the memory is not freed. Just by opening and closing the same pdf over and over I can get from 150 MB (normal memory usage of atom) up to 1.5 GB, or more.

If I try to replicate this on other normal files, it does appear that memory is (sooner or later) freed. This seems to be happening only on pdf files.

I am using Atom 1.19.0.

**Comment by izuzak** [comment]
Hi @adimol  👋. This sounds similar to another report: #72. Can you give that a read and add your comment there? I'd be happy to try and reproduce this again, but I'd need exact and detailed steps to reproduce and the exact documents you're reproducing this with, so that we could confirm if this is a problem with this package or not. I've tried to reproduce it before -- but was never able to. Thanks!

**Comment by Foggalong** [comment]
@izuzak I'm having this issue and reading through the linked issue it doesn't sounds like the same thing. For example, when I load up up a 5MB PDF (someone's PhD thesis) there's an increase in memory usage by just over 1GB which never frees up, even after the tab is closed, until Atom itself is closed.
 
![2018-11-25-135946_144x94_scrot](https://user-images.githubusercontent.com/5920259/48979960-6d1cfe00-f0ba-11e8-9bfa-a6407aa9418a.png)
(each dashed line is 2GB of RAM)

I've seen similar effects with smaller PDFs, just used a larger one here for better demonstrating it. Happy to provide as much details as needed to help with reproducing this :)
