### ISSUE TITLE
Synctex reverse does not work on Atom 1.31.2

### ISSUE THREAD

**Issue by mafw** [izuzak/atom-pdf-view#216]
Hello,

Unfortunately I can't get SyncTex reverse to work on Windows 10. When I click anywhere in the PDF viewer it simply opens a new blank text file with the same name.

The version of pdf-view is 0.71.0
The version of Atom is 0.50.0
Windows 10 build: 17134.320

Any help would be greatly appreciated!

**Comment by GitHubRulesOK** [comment]
That may be correct since, in any synctex enabled viewer
If you have a .pdf and a .synctex(.gz) then on triggering inverse search it expects to open in the configured editor the samename.tex so if its not in the same directory it may start blank.
This can be affected by configuration , relative vs absolute paths, synctex engine version and viewer embedment's. so to test you need all 3 files from the same compile in the same test folder .

**Comment by mafw** [comment]
That actually makes a lot of sense. I tested it now with a new .tex file and a fresh compile; it worked perfectly - so I'll close this thread. 

Thank you very much for your time and help!
