### ISSUE TITLE
Set initial zoom level to fit width of current buffer

### ISSUE THREAD

**Issue by afischer** [izuzak/atom-pdf-view#73]
It would be fantastic if pdf-view could set the initial zoom so that the PDF's width fit the width of the pane it is being opened in, preventing sideway scrolling.

**Comment by izuzak** [comment]
That's a really neat idea, @afischer -- I'd definitely like to see that ability in this package (but probably behind a config setting so that it doesn't disrupt someone's workflow).

I don't think I'll be able to dedicate time to this in the near future, but happy to review+merge a pull request if someone would like to tackle this.

Thanks for suggesting this :star2:

**Comment by michal-szostak** [comment]
I was also going to suggest this feature, but I see that someone thought about it earlier. I would actually recommend to give an option (maybe global one?) to enable / disable this kind of behaviour (for small screens it's very welcomed (as original size of the document usually doesn't fit) but for bigger ones it may not be so.

**Comment by nunocastromartins** [comment]
:+1:

**Comment by izuzak** [comment]
pdf-view 0.41.0 now has a config option for this, thanks to @nsaje :zap:

Thanks again for suggesting this
